services:
  db:
    image: postgres:17-alpine
    container_name: job_scraper_db
    restart: always
    environment:
      POSTGRES_DB: js_database
      POSTGRES_USER: js_user
      POSTGRES_PASSWORD: js_password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: job_scraper_app
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: js_database
      DB_USERNAME: js_user
      DB_PASSWORD: js_password
    depends_on:
      - db

volumes:
  db_data:
